### ISSUE TITLE
this.model.getLabel is not a function

### ISSUE THREAD

**Issue by tcs-apeters** [mpneuried/iggy#24] opened 2015-06-05 14:31 UTC
c.render@https://sb.brendisol.com/dynasite/vendor/plugins/iggy/js/iggy.js 9:17266  

```
f.length;
d > b;
c = ++b) e = f[c], a.push(e.getLabel());
return this.$el.html(this.template({
    label: this.model.getLabel(),
    selected: a
})), this.$sub = this.$(".subselect"), this.$results = this.$(".subresults"), this.gen
```

**Comment by mpneuried** [comment] 2015-06-09 06:11
i think here and in #23 there is an error within the configuration.
In both cases the error is caused by a not existing model.

Can you provide me with an example of your configuration, so i can reproduce this error?

**Comment by mpneuried** [comment] 2015-06-10 08:45
![bildschirmfoto 2015-06-10 um 10 44 09](https://cloud.githubusercontent.com/assets/300631/8078384/ca068d4e-0f5d-11e5-9667-2ce855afd993.png)

**Comment by mpneuried** [comment] 2017-01-26 14:07
@tcs-apeters, @trietz & @CitySim:
can we close this bug?

**Closed as completed** 2017-04-03 08:48 UTC
Labels: bug
